### ISSUE TITLE
[Bug]: 使用翻譯後出現意外的應用程式錯誤！

### ISSUE THREAD

**Issue by maronster** [immersive-translate/immersive-translate#1498]
### 插件版本号 | Version

1.2.4

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

當翻譯網頁後 進入該網頁的下一頁會跳出意外的應用程式錯誤！ 
無法在「Node」上執行「removeChild」：要刪除的節點不是此節點的子節點。
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Vc (https://venus.chub.ai/assets/index-4ce8d909.js:40:25994)
    at $e (https://venus.chub.ai/assets/index-4ce8d909.js:40:27283)
    at Hc (https://venus.chub.ai/assets/index-4ce8d909.js:40:27740)
    at $e (https://venus.chub.ai/assets/index-4ce8d909.js:40:27432)
    at Hc (https://venus.chub.ai/assets/index-4ce8d909.js:40:27740)
    at $e (https://venus.chub.ai/assets/index-4ce8d909.js:40:27432)
    at Hc (https://venus.chub.ai/assets/index-4ce8d909.js:40:27740)
    at $e (https://venus.chub.ai/assets/index-4ce8d909.js:40:27432)
    at Hc (https://venus.chub.ai/assets/index-4ce8d909.js:40:27545)
    at $e (https://venus.chub.ai/assets/index-4ce8d909.js:40:27432)

### 出现问题的网址 | URL

https://venus.chub.ai/home

**Comment by keyboard3** [comment]
是不是选择了仅译文？ 这是因为该站点采用了虚拟dom渲染技术，当选择仅译文的时候会改变原dom结构。这种站点只能双语对照显示
