### ISSUE TITLE
插件导致chatgpt崩溃

### ISSUE THREAD

**Issue by outwalllife** [immersive-translate/immersive-translate#471]
### 插件版本号 | Version

0.5.5

### 浏览器 | Browsers

Chrome

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

在chat.openai.com中运行时，很容易导致chatgpt崩溃。

### 重现步骤 | To Reproduce

概率性，测试概率估计是80%的可能性。
<img width="373" alt="image" src="https://github.com/immersive-translate/immersive-translate/assets/126863187/24afa8d8-db66-4315-bb53-194807ebda75">

### 补充说明 | Additional context

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
statsigapi.net/v1/sdk_exception:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
events.statsigapi.net/v1/rgstr:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
_app-ed62645498d9be19.js:14 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at uH (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:84991)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86232)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:87812)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86495)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
    at uq (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86692)
    at uQ (https://chat.openai.com/_next/static/chunks/framework-e23f030857e925d4.js:9:86382)
(anonymous) @ _app-ed62645498d9be19.js:14

**Comment by theowenyoung** [comment]
感谢反馈，这个问题我们正在重构核心的部分，next相关的网站有不少会有这个问题。预计下周发布的新版会彻底解决这个问题。

**Comment by keyboard3** [comment]
0.5.7 版本已经解决
